"""empty message

Revision ID: ef127d43de9e
Revises: b194900de828
Create Date: 2021-01-22 20:46:48.219170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef127d43de9e"
down_revision = "b194900de828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_transaction_id", "trades", ["transactionId"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_transaction_id", "trades", type_="unique")
    # ### end Alembic commands ###
