# Generated by Django 3.1.7 on 2021-03-22 05:51

from django.db import migrations, models
import django.db.models.deletion
import ibkr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.IntegerField()),
            ],
            bases=(models.Model, ibkr.models.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('asset_category', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.contract')),
            ],
            bases=(models.Model, ibkr.models.BaseModelMixin),
        ),
    ]
