# Generated by Django 3.1.7 on 2021-03-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cusip',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='isin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='issuer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='listing_exchange',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='multiplier',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='security_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='security_id_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='underlying_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='underlying_contract', to='ibkr.contract'),
        ),
        migrations.AddField(
            model_name='trade',
            name='underlying_listing_exchange',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='underlying_security_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='underlying_symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='ibkr.contract'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
