# Generated by Django 3.1.7 on 2021-04-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0002_auto_20210323_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transactionId',
            field=models.IntegerField(null=True),
        ),
    ]
