# Generated by Django 3.1.7 on 2021-04-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0003_trade_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='transactionId',
        ),
    ]
