# Generated by Django 3.1.7 on 2021-04-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0005_auto_20210405_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='transaction_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
