# Generated by Django 3.1.7 on 2021-04-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0006_auto_20210405_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
