# Generated by Django 3.1.7 on 2021-04-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0007_auto_20210406_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buy_sell',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fifo_pnl_realized',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fx_pnl',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='mtm_pnl',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_close_indicator',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
