# Generated by Django 3.1.7 on 2021-04-06 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0008_auto_20210406_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='executed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
