# Generated by Django 3.1.7 on 2021-04-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0009_trade_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=6, null=True),
        ),
    ]
