# Generated by Django 3.1.7 on 2021-04-11 18:29

from django.db import migrations, models
import django.db.models.deletion
import ibkr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0010_auto_20210411_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            bases=(models.Model, ibkr.models.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='GroupTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.group')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibkr.trade')),
            ],
            bases=(models.Model, ibkr.models.BaseModelMixin),
        ),
    ]
