# Generated by Django 3.1.7 on 2021-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0011_group_grouptrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='trades',
            field=models.ManyToManyField(through='ibkr.GroupTrade', to='ibkr.Trade'),
        ),
        migrations.AddField(
            model_name='trade',
            name='groups',
            field=models.ManyToManyField(through='ibkr.GroupTrade', to='ibkr.Group'),
        ),
    ]
