# Generated by Django 3.1.7 on 2021-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0013_auto_20210630_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='account_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
